### ISSUE TITLE
Open Setting Window can cause error when VRCSDK is exist

### ISSUE THREAD

**Issue by VRC-INYO** [Thryrallo/ThryEditor#1]
https://youtu.be/fsbEeRxoiMU
-
If I import all the scripts, then delete "Try Editor.cs", and start Unity again, and finally import "Thry Editor.cs" back again (at this time it will not appear pop-up window).
This will temporarily prevent me from seeing any errors during play mode
It accidentally resolved the error "temporarily" until I opened the settings of the Thry editor again.
After the above narrative I guess it should be related to a certain part of the setting window

**Comment by Thryrallo** [comment]
"Two delegators in existence." and "Destroy may not be called from edit mode! Use DestroyImmediate instead." are both thrown by the vrc sdk. it seems to be somewhat related to other scripts in away (recompiling or similar seems to cause these issues, not 100% sure), but it can only really be fixed by the vrchat devs.
